name: Check code cleanup

on:
  workflow_run:
    workflows: ["build"]
    types:
      - completed

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET Environment
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Install the dotnet-format tool
        run: dotnet tool install -g dotnet-format

      - name: Run dotnet-format
        run: dotnet format --check --verbosity detailed